### ISSUE TITLE
同款带wifi的主板可以正常安装吗

### ISSUE THREAD

**Issue by fun-li** [yzchan/MSI-MAG-B660M-MORTAR-DDR4-12600K-EFI#10]

**Comment by yzchan** [comment]
可以的，没有问题

**Comment by fangmoufu** [comment]
带wifi的主板好像要屏蔽自带的蓝牙端口，请问下  关闭小核是不是性能会好一些。

**Comment by yzchan** [comment]
> 带wifi的主板好像要屏蔽自带的蓝牙端口，请问下 关闭小核是不是性能会好一些。

开始也我觉得应该是这样。但是我测过，不管是关闭小核还是关闭超线程，跑分都会降低。所以现在都开着。

**Comment by fangmoufu** [comment]
请问下你这个CPU带核显   要不要做特殊操作屏蔽核显
另外你睡眠的时候风扇还转吗

**Comment by fun-li** [comment]
> 可以的，没有问题

好的 谢谢

**Comment by yzchan** [comment]
> 请问下你这个CPU带核显 要不要做特殊操作屏蔽核显 另外你睡眠的时候风扇还转吗

核显不需要屏蔽。我装的双系统，win10下使用核显也可以正常输出。

风扇特意看了一下，睡眠之后大概1分钟就停止了。

**Comment by fangmoufu** [comment]
1分钟睡眠后还能按鼠标键盘唤醒吗，我现在深度睡眠后只能按开机键唤醒

**Comment by yzchan** [comment]
> 1分钟睡眠后还能按鼠标键盘唤醒吗，我现在深度睡眠后只能按开机键唤醒

这是正常的。如果希望通过键鼠唤醒，BIOS开启“USB设备从S3/S4/S5唤醒”，并且打开ERP-Ready。
项目自述文档有写这个问题。
