### ISSUE TITLE
[已start] 迫击炮Wi-Fi成功安装12.4，但存在一些小问题，请求老哥帮助

### ISSUE THREAD

**Issue by lyq1996** [yzchan/MSI-MAG-B660M-MORTAR-DDR4-12600K-EFI#2]
第一次装黑苹果，花了1天时间研究了一下，你的EFI基本是很完美的，睡眠、后置usb、显卡、cpu跑分都很正常。

但我这里遇到两个问题，不知道你有没有遇到。

~第一个是我JUSB2也接的前面板的USB2.0接口，但u盘插上去不识别，只能用鼠标和键盘，我怀疑是前置接口接触不良。~(是我前面板接触不良）

第二个是我显卡是6800xt，所以`boot-args`加了`agdpmod=pikera`，但通过oc引导windows直接黑屏不显示了，f11用windows boot manager引导正常。虽然黑屏，但键盘鼠标是有反应，凭感觉输密码能进系统，也可以alt+f4关机。你有遇到这个问题吗？

另外你的安全启动是开的吗？我是关的。

**Comment by yzchan** [comment]
安全启动关闭的。
我也是双系统，win10用oc可以正常引导。
你用的是dp线还是hdmi线？黑屏问题跟我之前用hdmi引导另一台10400核显主机情况很类似，我也没解决。最后换dp线就好了。

**Comment by lyq1996** [comment]
> 

是dp线，现在在一个个配置的试，怕是无解了

**Comment by lyq1996** [comment]
我用duxphp的efi可以引导windows

https://github.com/duxphp/Hackintosh-12700KF-B660M-MORTAR-6600XT/commit/08d7a461803850f580530e07997e66d2833272ff 

这个提交说是修复启动问题，也没看出啥，难道是BOOTx86.efi的权限问题？

**Comment by lyq1996** [comment]
找到原因了，我uefi的ResizeGpuBars设置为0了，以为这个和booter里面都要设置为0 .. 

你的efi完美了，再次表示感谢！！
