### ISSUE TITLE
BCM9360蓝牙功能不正常

### ISSUE THREAD

**Issue by monkiq** [yzchan/MSI-MAG-B660M-MORTAR-DDR4-12600K-EFI#3]
同款msi b660m搭配12700, BIOS里屏蔽了wifi和蓝牙,使用pcie接奋威的t919,也是免驱的,
现在问题是: 我的蓝牙一连接iphone就会断开,但是隔空,接力正常,随航没法用.系统里显示蓝牙是这样的,请问你的系统里蓝牙也是显示在hub下面吗, hackintool也检测不到蓝牙,只能检测到usb2.0 hub
<img width="654" alt="image" src="https://user-images.githubusercontent.com/27727951/174229078-137a4e25-d17f-4155-8187-bc8657d105a9.png">

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/27727951/174229320-40ad4694-f23a-4d7f-95ee-002982c7dc14.png">
<img width="483" alt="image" src="https://user-images.githubusercontent.com/27727951/174229412-127a8b95-65a9-43ca-995d-e1f776722bee.png">

**Comment by yzchan** [comment]
<img width="907" alt="iShot_2022-06-17_21 01 52" src="https://user-images.githubusercontent.com/8966088/174304227-c2ab84b6-3750-4d8c-b95a-650f1236f20f.png">
<img width="506" alt="iShot_2022-06-17_21 03 42" src="https://user-images.githubusercontent.com/8966088/174304237-1e838d85-766c-4d6d-8c0c-d42661cbb504.png">
<img width="950" alt="iShot_2022-06-17_21 04 10" src="https://user-images.githubusercontent.com/8966088/174304241-c173c4b5-d048-4c5c-8fc5-644ded8fd3ba.png">

跟你一样的。

没有iphone没试过随航。使用蓝牙键鼠正常吗？

**Comment by monkiq** [comment]
蓝牙鼠标正常的,mx master3.ipad和iphone都连接不上,不过安卓倒是可以

**Comment by yzchan** [comment]
下周我借个苹果手机试试随航

**Comment by lyq1996** [comment]
没核显的用不了随航好像

**Comment by monkiq** [comment]
主要就是跟iphone蓝牙连接不上,我初步怀疑是hub的问题,因为msi b660m的主板上那两个usb 9针的接口都是hub,现在淘宝买了一个9针转外置usb的,明天试试看

**Comment by lyq1996** [comment]
> 主要就是跟iphone蓝牙连接不上,我初步怀疑是hub的问题,因为msi b660m的主板上那两个usb 9针的接口都是hub,现在淘宝买了一个9针转外置usb的,明天试试看

主板上两个9针usb确实是在hub下，我也是T919，试了一下，蓝牙可以和ipad连上 😂

**Comment by monkiq** [comment]
> 

啊这,你也是Monterey吗,我的和ipad也连接不上.提示不支持此Mac,你也是12代配置吗,方便发个EFI吗,我试试你的

**Comment by lyq1996** [comment]
> > 
> 
> 啊这,你也是Monterey吗,我的和ipad也连接不上.提示不支持此Mac,你也是12代配置吗,方便发个EFI吗,我试试你的

是Monterey，迫击炮wifi+12700+6800xt，T919系统里面信息跟你一样，我的EFI里面的usb映射直接用的po主的，只是改了一点oc配置。

https://github.com/lyq1996/MSI-B660M-MORTAR-WIFI-HACKINTOSH

**Comment by monkiq** [comment]
试了这个EFI也是没用,不过隔空投送倒是好的,试了试iPhone连接ipad也是提示不支持此设备,看了[https://discussionschinese.apple.com/thread/253206230](https://discussionschinese.apple.com/thread/253206230)这个,好像连不上也挺正常.

**Comment by yzchan** [comment]
> 试了这个EFI也是没用,不过隔空投送倒是好的,试了试iPhone连接ipad也是提示不支持此设备,看了https://discussionschinese.apple.com/thread/253206230这个,好像连不上也挺正常.

试了下iphone连接的确一连就断。安卓正常。可能确实就是这么设计的。

我感觉只要试下能不能连接苹果airpods，能正常使用就是ok的。可惜我没有😂

**Comment by monkiq** [comment]
> 

可以连接其他蓝牙设备也是ok的,比如耳机,键盘还有鼠标

**Comment by wenbo1** [comment]
> > 
> 
> 可以连接其他蓝牙设备也是ok的,比如耳机,键盘还有鼠标

我拿白苹果也连不上iPhone😂
