### ISSUE TITLE
对于12700需要改哪些配置，能给下建议吗

### ISSUE THREAD

**Issue by lishouxian** [yzchan/MSI-MAG-B660M-MORTAR-DDR4-12600K-EFI#5]

**Comment by yzchan** [comment]
把NVRAM里把revcpuname改成自己的CPU型号（这个只影响CPU的显示）。

使用CPUFriend.kext生成CPU动态睿频电源管理数据。可以参考>>[这个视频](https://www.bilibili.com/video/BV1NL4y1j7yj?spm_id_from=333.999.0.0&vd_source=9e10d2ba06b29f4c69a421064afcc12a)<<。
然后用Geekbench之类的软件测下跑分，打开Intel Power Gadget看看睿频是否正常。

主板一样的话我这个EFI应该是可以直接用的。
https://github.com/duxphp/Hackintosh-12700KF-B660M-MORTAR-6600XT 这个也可以参考一下。

**Comment by lishouxian** [comment]
好的，非常感谢你的建议
