### ISSUE TITLE
电脑休眠之后，蓝牙崩溃不可用

### ISSUE THREAD

**Issue by junguoguo2017** [yzchan/MSI-MAG-B660M-MORTAR-DDR4-12600K-EFI#6]
电脑休眠以后，点电源键，然后系统偏好设置打开蓝牙卡顿、崩溃。  我的网卡是bcm94352z

**Comment by yzchan** [comment]
我试了下我的BCM94360CD是没问题的。给EFI里面添加蓝牙增强驱动试试呢

**Comment by junguoguo2017** [comment]
> 我试了下我的BCM94360CD是没问题的。给EFI里面添加蓝牙增强驱动试试呢


用哪个蓝牙增强驱动？目前我用的是AirportBrcmFixup.kext跟BlueToolFixup.kext， 休眠启动之后，蓝牙设置进不去，蓝牙不可用，wifi是正常的。只有把蓝牙关闭重新开启，过一会才可以。

**Comment by yzchan** [comment]
蓝牙是要靠usb供电的，睡眠之后蓝牙奔溃我猜是跟usb的供电有关系。给蓝牙换一个usb口试试，或者打开bios里面的"USB设备从S3/S4/S5唤醒"。

https://bbs.pcbeta.com/viewthread-1909781-1-1.html  这里面的情况感觉跟你描述的类似，也可以参考一下

**Comment by junguoguo2017** [comment]
> “usb设备从s3/s4/s5唤醒”设置了没用。 远景什么关闭xmp,我的xmp本来就是关闭的。手动超频的。  两个都试了没用。我退回到11.6正常了。

**Comment by junguoguo2017** [comment]
买了fenv t919 现在蓝牙正常了。
