### ISSUE TITLE
12600k使用intel的工具查看，最高频率只有3.8，应该怎么办

### ISSUE THREAD

**Issue by East333** [yzchan/MSI-MAG-B660M-MORTAR-DDR4-12600K-EFI#7]
12600k+铭瑄h610itx，使用Intel power gadget查看，频率的max只有3.8，大佬你的是4.9，我该怎么办，能指点一下吗，要哭了

**Comment by yzchan** [comment]
需要自己定制CPUFriendDataProvider.kext驱动的。看下这个up主的 [原生电源管理](https://www.bilibili.com/video/BV1NL4y1j7yj) 教程。
也可以用本仓库里的CPUFriendDataProvider.kext试一试。

另外你这个h610itx的供电能跑满12600k的睿频么？最好进win测试一下。

**Comment by East333** [comment]
嗯好的，我用你的kext试一下，在win下烤鸡可以达到小核心3.8大核心4.5稳定，跑满应该是没问题的，现在最大睿频变成了小核心的最高频率了，昨天搞了一天，今天换换efi试试

**Comment by yzchan** [comment]
主板不同直接用我的efi肯定是不行的。只需要把你现在能进系统的efi替换成我的CPUFriendDataProvider.kext试一下。

**Comment by East333** [comment]
好的好的，我试一下，谢谢你啦

**Comment by East333** [comment]
太好了，终于搞好了，我用你的CPUFriendDataProvider解决了这个问题了，我还有两个问题想麻烦问你一下，你的cpu的温度传感器可以正常识别温度吗，就是精确到每个核心的温度。还有就是大佬你有用CpuTopologyRebuild.kext加启动参数来识别核心吗，你现在是识别的6核心16线程，还是10核心16线程，还是16核心16线程呢

**Comment by yzchan** [comment]
我记得是10核心16线程（不太确定）。我晚上回去再看一下。

**Comment by yzchan** [comment]
这是Geekbench5 [macOS](https://browser.geekbench.com/v5/cpu/15421364) 和 [window10](https://browser.geekbench.com/v5/cpu/15023510) 的跑分结果。Topology一项win10正常，macOS下似乎识别不对。

**Comment by yzchan** [comment]
这是sensei的温度传感器结果
<img width="1253" alt="iShot_2022-07-18_21 03 26" src="https://user-images.githubusercontent.com/8966088/179519723-1f481295-d251-4ab2-8d98-87f80f8a1b8e.png">

**Comment by East333** [comment]
你的这个mac单核分数也太高了吧，我的天

**Comment by yzchan** [comment]
我看过好多其他人的12600k跑分，基本都是1700~1900多

**Comment by East333** [comment]
可以可以，这两天麻烦你啦

**Comment by yzchan** [comment]
不客气，感觉有帮助的话也可以帮我点个star😊

**Comment by youngmisir** [comment]
> 12600k+铭瑄h610itx，使用Intel power gadget查看，频率的max只有3.8，大佬你的是4.9，我该怎么办，能指点一下吗，要哭了

你现在解决了吗？我是12700+微星b660m迫击炮D4，原来也是只有3.8，也自己定制了CPUfrienddataprovider.kext，然而还是照样最大频率3.8。换成了这个EFI后，就变成4.9了。

**Comment by East333** [comment]
我和你的情况一样，自己定制cpufrinenddataprovider.kext不管用，换了这个dataprovider.kext就好了
