### ISSUE TITLE
隔空投屏支持吗

### ISSUE THREAD

**Issue by yegetables** [yzchan/MSI-MAG-B660M-MORTAR-DDR4-12600K-EFI#8]
听说因为没有核显加速所以不能隔空投屏，过几天本来想组一台，犹豫了

**Comment by yzchan** [comment]
这个功能没用过，怎么操作的? 
隔空投送是可以的，有蓝牙和wifi就行。

**Comment by yegetables** [comment]
> 这个功能没用过，怎么操作的? 隔空投送是可以的，有蓝牙和wifi就行。

应该是随行功能,ipad投屏这样的.这几天看大家都在说12代黑苹果有这个问题

**Comment by yzchan** [comment]
听说是这样的，随航没核显用不了。我没有ipad也没法实测。
